name: Deploy to GitHub Pages  # Name of the workflow

on:  # Defines the event that triggers the workflow
  push:  # The workflow is triggered when code is pushed
    branches: ["main"]  # The workflow is triggered when code is pushed to the main branch
  workflow_dispatch:  # The workflow can also be triggered manually
    inputs:
      headerTitle:
        description: 'Header Title'  # Description of the input
        required: true  # The input is required
permissions:  # Defines the permissions for the GitHub token used in this workflow
  contents: read  # Read access to the repository contents
  pages: write  # Write access to pages
  id-token: write  # Write access to id-token

concurrency:  # Ensures that only one job or workflow using the same concurrency group will run at a time
  group: "pages"  # Name of the concurrency group
  cancel-in-progress: false  # If another job or workflow using the "pages" concurrency group starts, it will be pending until the running job finishes

jobs:  # Defines the jobs in the workflow
  build:  # Name of the first job
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu
    steps:  # Defines the steps in the job
      - name: Checkout  # Name of the first step
        uses: actions/checkout@v4  # Checks out your repository
      - name: Setup Node.js environment  # Name of the second step
        uses: actions/setup-node@v4.0.2  # Sets up a Node.js environment on the runner
      - name: Install dependencies  # Name of the third step
        run: npm install  # Installs the project dependencies
      - name: Build  # Name of the fourth step
        env:  # Defines environment variables for this step
          REACT_APP_HEADER: ${{ github.event.inputs.headerTitle || 'Default Header' }}  # Sets the REACT_APP_HEADER environment variable to the value of the headerTitle input if it's set, otherwise uses 'Default Header'
        run: npm run build  # Builds the project
      - name: Setup Pages  # Name of the fifth step
        uses: actions/configure-pages@v5  # Sets up GitHub Pages for the project
      - name: Build with Jekyll  # Name of the sixth step
        uses: actions/jekyll-build-pages@v1  # Builds the site with Jekyll
        with:  # Specifies the parameters for the action
          source: ./build  # The source directory
          destination: ./_site  # The destination directory
      - name: Upload artifact  # Name of the seventh step
        uses: actions/upload-pages-artifact@v3  # Uploads the build artifact (the _site directory)

  deploy:  # Name of the second job
    environment:  # Defines the environment for the job
      name: github-pages  # Name of the environment
      url: ${{ steps.deployment.outputs.page_url }}  # The URL of the deployed site
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu
    needs: build  # The job depends on the build job
    steps:  # Defines the steps in the job
      - name: Deploy to GitHub Pages  # Name of the first step
        id: deployment  # The ID of the step
        uses: actions/deploy-pages@v4  # Deploys the site to GitHub Pages